[build]
  command = "npm run build" 
  publish = "/" 

[[headers]]
  for = "/*.js"
  [headers.values]
  Content-Type = "text/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
  Content-Type = "text/css"
